### ISSUE TITLE
coveralls not responding on pull requests / python

### ISSUE THREAD

**Issue by kapilt** [lemurheavy/coveralls-public#1207]
Hi Folks,

for the last week or so, coveralls has not been responding on our pull requests on our project. Its currently a mandatory check there.  We're directly pushing to coveralls from travis ci. Any suggestions on how to rectify would be appreciated.

Project
https://github.com/capitalone/cloud-custodian/pulls

Some pull requests as examples
https://github.com/capitalone/cloud-custodian/pull/3001
https://github.com/capitalone/cloud-custodian/pull/2993
https://github.com/capitalone/cloud-custodian/pull/2995
https://github.com/capitalone/cloud-custodian/pull/2955

the coveralls integration to travis is pretty standard
https://github.com/capitalone/cloud-custodian/blob/master/.travis.yml

and completes without error.. oh wait it does error.

```
0.18s$ if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then coveralls; fi
/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/coveralls", line 7, in <module>
    from coveralls.cli import main
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/coveralls/__init__.py", line 2, in <module>
    from .api import Coveralls
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/coveralls/api.py", line 9, in <module>
    import requests
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/compat.py", line 48, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
```

hmm.. so this is python specific, and a dependency issue for coveralls python package, filing the bug report got me looking into the details a bit more :-), hopefully its helpful to others. i'll update if i can find a resolution, it looks like we need an appropriate version pin for requests/urllib3 on python2

**Comment by kapilt** [comment]
underlying issue documentation 
https://github.com/urllib3/urllib3/issues/1456

looks like requests package is prepping for a release that will address 
https://github.com/requests/requests/pull/4835

**Comment by kapilt** [comment]
resolved upstream
