### ISSUE TITLE
500 Server Error is not operational

### ISSUE THREAD

**Issue by colecrtr** [lemurheavy/coveralls-public#1315]
```
Submitting coverage to coveralls.io...
Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/coveralls/api.py", line 175, in wear
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/coveralls/cli.py", line 77, in main
    result = coverallz.wear()
  File "/usr/local/lib/python3.6/site-packages/coveralls/api.py", line 178, in wear
    raise CoverallsException('Could not submit coverage: {}'.format(e))
coveralls.exception.CoverallsException: Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
```

Yet the Coveralls status page shows everything as "Operational": https://status.coveralls.io/

**Comment by lsanders** [comment]
#1317 is also a duplicate

**Comment by nickmerwin** [comment]
Hi @colecrtr we recently fixed an issue with a deprecated BitBucket API endpoint -- can you trigger another build now please?

**Comment by colecrtr** [comment]
Hey @nickmerwin, Coverage is now submitting perfectly. Thanks for being so responsive :+1:
