### ISSUE TITLE
500 Build processing error. while reporting.

### ISSUE THREAD

**Issue by lsanders** [lemurheavy/coveralls-public#1317]
We've been getting this error for about 24 hrs. Synchronizing repos had no affect. Coveralls status page indicates no problems in last 24 hours. 

Build's coming from bitbucket pipelines, if that matters.

**Comment by nickmerwin** [comment]
Hi @lsanders can you trigger another build now please?

**Comment by Themanwithoutaplan** [comment]
I'm seeing this as well. This is the traceback from our BitBucket pipelines

```

cov runtests: commands[1] | coveralls
Submitting coverage to coveralls.io...
Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/opt/atlassian/pipelines/agent/build/.tox/cov/lib/python3.6/site-packages/coveralls/api.py", line 177, in wear
    response.raise_for_status()
  File "/opt/atlassian/pipelines/agent/build/.tox/cov/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/atlassian/pipelines/agent/build/.tox/cov/lib/python3.6/site-packages/coveralls/cli.py", line 77, in main
    result = coverallz.wear()
  File "/opt/atlassian/pipelines/agent/build/.tox/cov/lib/python3.6/site-packages/coveralls/api.py", line 180, in wear
    raise CoverallsException('Could not submit coverage: {}'.format(e))
coveralls.exception.CoverallsException: Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
ERROR: InvocationError for command '/opt/atlassian/pipelines/agent/build/.tox/cov/bin/coveralls' (exited with code 1)
```

**Comment by lsanders** [comment]
@Themanwithoutaplan  - this was broke and resolved and now broke again. New issue is #1322 and I'm hoping they'll respond soon :)

**Comment by nickmerwin** [comment]
Hi @Themanwithoutaplan and @lsanders we're working on a fix right now.
