### ISSUE TITLE
Did you mean?  coverage_data

### ISSUE THREAD

**Issue by Applifort** [lemurheavy/coveralls-public#1405]
Hi

I have simple rails app. And try to configure coveralls for tests. My test_helper looks like:

```
ENV['RAILS_ENV'] ||= 'test'
require 'coveralls'
Coveralls.wear!

require_relative '../config/environment'
require 'rails/test_help'

class ActiveSupport::TestCase
  include FactoryBot::Syntax::Methods
  include AuthHelper
end
```
When I run rails test, I've got this error:
```
Coveralls encountered an exception:
NoMethodError
undefined method `coverage' for #<SimpleCov::SourceFile:0x0000563480e56ab8>
Did you mean?  coverage_data
/bundle_cache/ruby/2.7.0/gems/coveralls-0.7.1/lib/coveralls/simplecov.rb:50:in `block in format'
/usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `each'
/usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `each'
/bundle_cache/ruby/2.7.0/gems/coveralls-0.7.1/lib/coveralls/simplecov.rb:40:in `format'
/bundle_cache/ruby/2.7.0/gems/simplecov-0.18.2/lib/simplecov/result.rb:49:in `format!'
/bundle_cache/ruby/2.7.0/gems/simplecov-0.18.2/lib/simplecov/configuration.rb:196:in `block in at_exit'
/bundle_cache/ruby/2.7.0/gems/simplecov-0.18.2/lib/simplecov.rb:201:in `run_exit_tasks!'
/bundle_cache/ruby/2.7.0/gems/simplecov-0.18.2/lib/simplecov/defaults.rb:31:in `block in <main>'

```
I searched a lot in google, aldo tried to configure simplecov, but error the same. Could you help me?

**Comment by afinetooth** [comment]
@Applifort, right now Coveralls is incompatible with some later versions of simplecov. We'll be addressing that soon, but in the meantime, the workaround is to explicitly call and lock the version of simplecov in your Gemfile, like so:

`gem "simplecov", "0.16"`

Try that and let me know if it doesn't work.
