### ISSUE TITLE
coverage: 504 Server Error: Gateway Time-out for url: https://coveralls.io/api/v1/jobs

### ISSUE THREAD

**Issue by ebattat** [lemurheavy/coveralls-public#1675]
All working properly till today.
Starting to get this error in our CI.

```
Installing collected packages: docopt, coveralls
  Running setup.py install for docopt: started
  Running setup.py install for docopt: finished with status 'done'
Successfully installed coveralls-3.3.1 docopt-0.6.2
Submitting coverage to coveralls.io...
Could not submit coverage: 504 Server Error: Gateway Time-out for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/coveralls/api.py", line [29](https://github.com/redhat-performance/benchmark-runner/actions/runs/3621976634/jobs/6107085812#step:8:30)0, in submit_report
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/coveralls/cli.py", line 95, in main
    result = coverallz.wear()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/coveralls/api.py", line 257, in wear
    return self.submit_report(json_string)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/coveralls/api.py", line 293, in submit_report
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 504 Server Error: Gateway Time-out for url: https://coveralls.io/api/v1/jobs
Error: Process completed with exit code 1.
```

Do you have any idea what can cause this error ?

**Comment by sidarth164** [comment]
I'm also getting a Gateway Time-out on our CI
```
[..................] / rollbackFailedOptional: verb npm-session b2cfeed1c61d904[[K..................] / rollbackFailedOptional: verb npm-session b2cfeed1c61d904[[K..................] - rollbackFailedOptional: verb npm-session b2cfeed1c61d904[[K..................] | fetchMetadata: sill resolveWithNewModule coveralls@3.1.1[[K..................] | fetchMetadata: sill resolveWithNewModule coveralls@3.1.1[[K..................] / fetchMetadata: sill resolveWithNewModule coveralls@3.1.1npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[..................] / fetchMetadata: sill resolveWithNewModule lcov-parse@1.0.[[K..................] \ fetchMetadata: sill resolveWithNewModule lcov-parse@1.0.[[K..................] / fetchMetadata: sill resolveWithNewModule argparse@1.0.10[[K   ...............] / fetchMetadata: sill resolveWithNewModule sprintf-js@1.0.[[K   ...............] / fetchMetadata: sill resolveWithNewModule sprintf-js@1.0.[[K   ...............] | fetchMetadata: sill resolveWithNewModule sprintf-js@1.0.npm WARN deprecated har-validator@5.1.5: this library is no longer supported
[   ...............] - fetchMetadata: WARN deprecated har-validator@5.1.5: this[[K   ...............] - fetchMetadata: WARN deprecated har-validator@5.1.5: this[[K   ...............] / fetchMetadata: WARN deprecated har-validator@5.1.5: thisnpm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[   ...............] \ fetchMetadata: sill resolveWithNewModule safe-buffer@5.2[[K   ...............] \ loadDep:mime-types: sill resolveWithNewModule delayed-st[[K   ...............] \ fetchMetadata: sill resolveWithNewModule asynckit@0.4.0[[K   ...............] \ fetchMetadata: sill resolveWithNewModule mime-db@1.52.0[[K   ...............] / fetchMetadata: sill resolveWithNewModule mime-db@1.52.0[[K   ...............] - fetchMetadata: sill resolveWithNewModule har-schema@2.0.[[K   ...............] / fetchMetadata: sill resolveWithNewModule har-schema@2.0.[[K   ...............] \ fetchMetadata: sill resolveWithNewModule fast-deep-equal[[K   ...............] \ fetchMetadata: sill resolveWithNewModule punycode@2.1.1[[K   ...............] \ fetchMetadata: sill resolveWithNewModule punycode@2.1.1[[K   ...............] \ fetchMetadata: sill resolveWithNewModule sshpk@1.17.0 ch[[K   ...............] / fetchMetadata: sill resolveWithNewModule sshpk@1.17.0 ch[[K   ...............] / loadDep:extsprintf: sill resolveWithNewModule verror@1.1[[K   ...............] \ fetchMetadata: sill resolveWithNewModule core-util-is@1.[[K   ...............] \ fetchMetadata: sill resolveWithNewModule core-util-is@1.[[K   ...............] \ loadDep:punycode: sill resolveWithNewModule jsbn@0.1.1 c[[K   ...............] / loadDep:punycode: sill resolveWithNewModule jsbn@0.1.1 c[[K       ...........] - postinstall: sill install executeActions[[K       ...........] \ extract:coveralls: verb lock using /root/.npm/_locks/sta[[K       ...........] \ extract:coveralls: verb lock using /root/.npm/_locks/sta[[K       ...........] \ extract:coveralls: verb lock using /root/.npm/_locks/sta[[K       ...........] \ extract:coveralls: verb lock using /root/.npm/_locks/sta[[K       ...........] / extract:coveralls: verb lock using /root/.npm/_locks/sta[[K        ..........] / extract:delayed-stream: sill extract extend@~3.0.2 extra[[K         .........] / extract:aws4: sill extract jsprim@^1.2.2 extracted to /u[[K          ........] - extract:asynckit: sill extract asynckit@^0.4.0 extracted[[K           .......] \ extract:lcov-parse: sill extract lcov-parse@^1.0.0 extra[[K            ......] \ extract:uri-js: sill extract uri-js@^4.2.2 extracted to[[K            ......] - finalize:safe-buffer: sill finalize /usr/local/lib/node_[[K            ......] | finalize:request: sill finalize /usr/local/lib/node_modu[[K            ......] | refresh-package-json:coveralls: timing action:finalize C[[K            ......] | refresh-package-json:coveralls: timing action:finalize C[[K            ......] / refresh-package-json:js-yaml: sill refresh-package-json[[K            ......] / build:har-validator: sill linkStuff har-validator@5.1.5/usr/local/bin/coveralls -> /usr/local/lib/node_modules/coveralls/bin/coveralls.js
+ coveralls@3.1.1
added 55 packages from 80 contributors in 2.616s

/usr/local/lib/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 504 <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

Is there a graceful way to handle it? Or do I have to rely on forking your github repo with my own fix?

**Comment by afinetooth** [comment]
Hi @ebattat @sidarth164, yes, we've had a recent incident starting yesterday late afternoon, US PDT, and continuing, with some respite, into this morning.

You can read more about the incident here:
https://status.coveralls.io/incidents/0xllsk9v8tpx

We are aware and working on it now.

**Comment by afinetooth** [comment]
Closing this. Thanks.
