### ISSUE TITLE
coveralls and travis: 400 Bad Request

### ISSUE THREAD

**Issue by MarioRuiz** [lemurheavy/coveralls-public#1696]
I'm getting Bad Request on the travis job for all my public repos.
```[Coveralls] Submitting to https://coveralls.io/api/v1
Coveralls encountered an exception:
JSON::ParserError
unexpected token at '<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
'
/home/travis/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
/home/travis/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
/home/travis/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/common.rb:569:in `load'
/home/travis/.rvm/gems/ruby-3.1.2/gems/coveralls-0.8.23/lib/coveralls/api.rb:31:in `post_json'
/home/travis/.rvm/gems/ruby-3.1.2/gems/coveralls-0.8.23/lib/coveralls/simplecov.rb:64:in `format'
/home/travis/.rvm/gems/ruby-3.1.2/gems/simplecov-0.16.1/lib/simplecov/result.rb:48:in `format!'
/home/travis/.rvm/gems/ruby-3.1.2/gems/simplecov-0.16.1/lib/simplecov/configuration.rb:182:in `block in at_exit'
/home/travis/.rvm/gems/ruby-3.1.2/gems/simplecov-0.16.1/lib/simplecov.rb:200:in `run_exit_tasks!'
/home/travis/.rvm/gems/ruby-3.1.2/gems/simplecov-0.16.1/lib/simplecov/defaults.rb:27:in `block in <top (required)>'
```

**Comment by afinetooth** [comment]
@MarioRuiz are you still getting this error?

We've seen this occasionally when file uploads are too large or DNS info is cached locally. Is this the first time you're posting from this repo in a while?

If you don't mind sharing your Coveralls Repo URL we'll look into it more closely.

**Comment by MarioRuiz** [comment]
No I post often there and other repos I have, all with the same issue.
Ok I managed to solved by not using the coveralls gem but coveralls_reborn
