### ISSUE TITLE
503 error when submitting coverage

### ISSUE THREAD

**Issue by ionelmc** [lemurheavy/coveralls-public#244]
Example (from build https://travis-ci.org/ionelmc/python-aspectlib/jobs/20172095 ):

```
.
Name                     Stmts   Miss Branch BrMiss  Cover   Missing
--------------------------------------------------------------------
src/aspectlib/__init__     251     25    119     15    89%   4-5, 20-21, 30, 214-220, 222-230, 296, 301, 322, 327
src/aspectlib/debug         59      0     32      7    92%   
src/aspectlib/test          38      0      8      0   100%   
--------------------------------------------------------------------
TOTAL                      348     25    159     22    91%   
----------------------------------------------------------------------
Ran 55 tests in 2.095s

OK (SKIP=2)
___________________________________ summary ____________________________________
[32m  pypy: commands succeeded[0m
[32m  congratulations :)[0m

The command "tox -v -e $TRAVIS_PYTHON_VERSION -- nosetests --with-cov --cover-branch --cover-erase --cover-package=aspectlib\*" exited with 0.
travis_fold:start:after_success
$ .tox/$TRAVIS_PYTHON_VERSION/bin/coveralls
Submitting coverage to coveralls.io...
Coverage submitted!
Failure to submit data. Response [503]: <!DOCTYPE html>
    <html>
    <head>
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="https://s3.amazonaws.com/assets.coveralls.io/maintenance.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File ".tox/pypy/bin/coveralls", line 11, in <module>
    sys.exit(main())
  File "/home/travis/build/ionelmc/python-aspectlib/.tox/pypy/site-packages/coveralls/cli.py", line 52, in main
    log.info(result['url'])
KeyError: 'url'
travis_fold:end:after_success
```

**Comment by sochka** [comment]
+1, but 504 error

**Comment by albertorestifo** [comment]
+1
