### ISSUE TITLE
use of coverageAggregate

### ISSUE THREAD

**Issue by mediavrog** [lemurheavy/coveralls-public#462]
We configured our project with subprojects and want to use the coverage reports properly.

We therefore followed the instructions for the sbt-scoverage and configured

1) coverage settings in build.sbt
2) configured travis to run `coverageAggregate` after writing the reports and upload to coveralls like
```
script: sbt clean coverage test
after_success: sbt coverageAggregate coveralls
```

but still the report in coveralls only shows the coverage report for the first submodule.

There was also an error thrown:

```
[info] Loading project definition from /home/travis/build/company/backend/project
[info] Set current project to backend (in build file:/home/travis/build/company/backend/)
[info] Aggregating coverage from subprojects...
[info] Found 2 subproject report files [/home/travis/build/company/backend/core/target/scala-2.11/scoverage-report/scoverage.xml,/home/travis/build/company/backend/target/scala-2.11/scoverage-report/scoverage.xml]
[info] Generating scoverage reports...
[info] Written Cobertura report [/home/travis/build/company/backend/target/scala-2.11/coverage-report/cobertura.xml]
[info] Written XML coverage report [/home/travis/build/company/backend/target/scala-2.11/scoverage-report/scoverage.xml]
[info] Written HTML coverage report [/home/travis/build/company/backend/target/scala-2.11/scoverage-report/index.html]
[info] Coverage reports completed
[info] Aggregation complete. Coverage was [72.90]
[success] Total time: 4 s, completed Feb 16, 2015 5:52:04 AM
[info] Repository = ./.git
[info] Repository = ./.git
[info] Uploading to coveralls.io succeeded: Job #803.1
[info] https://coveralls.io/jobs/4477298
[info] (results may not appear immediately)
java.lang.StringIndexOutOfBoundsException: String index out of range: -7
	at java.lang.String.substring(String.java:1911)
	at org.scoverage.coveralls.CoverallsClient.postFile(CoverallsClient.scala:38)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$projectSettings$8.apply(CoverallsPlugin.scala:112)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$projectSettings$8.apply(CoverallsPlugin.scala:61)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (root/*:coveralls) java.lang.StringIndexOutOfBoundsException: String index out of range: -7
```

**Comment by agile-jordi** [comment]
I've found the very same issue in a single project repo:

    java.lang.StringIndexOutOfBoundsException: String index out of range: -7

**Comment by nickmerwin** [comment]
Hi guys, I this issue would be better taken up with the authors of the Coveralls integration library you're using.

Sorry I can't be of more help!
