### ISSUE TITLE
RestClient::UnprocessableEntity 422 Unprocessable Entity {"message":"Couldn't find a repository matching this job.","error":true}

### ISSUE THREAD

**Issue by geokira** [lemurheavy/coveralls-public#640]
My repo: https://github.com/geokira/UberStatus

I recently added Coveralls to my repository in github. I am using Travis CI and Coveralls. Not sure where is the problem. Below is the error I am getting. Any help will be appreciated: 

````
[Coveralls] Submitting to https://coveralls.io/api/v1
Coveralls encountered an exception:
RestClient::UnprocessableEntity
422 Unprocessable Entity
/home/travis/build/geokira/UberStatus/vendor/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
/home/travis/build/geokira/UberStatus/vendor/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
/home/travis/build/geokira/UberStatus/vendor/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
/home/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:853:in `start'
/home/travis/build/geokira/UberStatus/vendor/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/home/travis/build/geokira/UberStatus/vendor/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/home/travis/build/geokira/UberStatus/vendor/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/home/travis/build/geokira/UberStatus/vendor/bundle/ruby/2.2.0/gems/coveralls-0.8.3/lib/coveralls/api.rb:23:in `post_json'
/home/travis/build/geokira/UberStatus/vendor/bundle/ruby/2.2.0/gems/coveralls-0.8.3/lib/coveralls/simplecov.rb:72:in `format'
/home/travis/build/geokira/UberStatus/vendor/bundle/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/result.rb:46:in `format!'
/home/travis/build/geokira/UberStatus/vendor/bundle/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/configuration.rb:159:in `block in at_exit'
/home/travis/build/geokira/UberStatus/vendor/bundle/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:60:in `call'
/home/travis/build/geokira/UberStatus/vendor/bundle/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:60:in `block in <top (required)>'
{"message":"Couldn't find a repository matching this job.","error":true}
````

**Comment by geokira** [comment]
I fixed my issue. I changed the coveralls.yml from travis-pro to travis-ci. Sorry for opening the issue.
